CREATE SCHEMA IF NOT EXISTS APPDATA;

CREATE TABLE APPDATA.SETTING
(
    ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
    NAME VARCHAR(32) NOT NULL,
    VALUE VARCHAR(512)
);

COMMENT ON TABLE APPDATA.SETTING IS 'Application settings. Key-value map structure.';
COMMENT ON COLUMN APPDATA.SETTING.NAME IS 'Setting name.';
COMMENT ON COLUMN APPDATA.SETTING.VALUE IS 'Setting value. Can be null, empty.';


CREATE TABLE APPDATA.PROJECT
(
    ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
    NAME VARCHAR(128) NOT NULL,
    APPVERSION VARCHAR(36),
    DESCRIPTION VARCHAR(512),
    KAFKAVERSION VARCHAR(36) NOT NULL,
    STATUS VARCHAR(36) CHECK (STATUS IN ('active', 'archived')),
    CREATEDTIME TIMESTAMP NOT NULL DEFAULT NOW(),
    MODIFEDTIME TIMESTAMP NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE APPDATA.PROJECT IS 'Kafka testing project. Contain info about testing project';
COMMENT ON COLUMN APPDATA.PROJECT.NAME IS 'Project name. Can not be null';
COMMENT ON COLUMN APPDATA.PROJECT.APPVERSION IS 'Project app version.';
COMMENT ON COLUMN APPDATA.PROJECT.DESCRIPTION IS 'Project description.';
COMMENT ON COLUMN APPDATA.PROJECT.KAFKAVERSION IS 'Project kafka testing version. Can not be null.';
COMMENT ON COLUMN APPDATA.PROJECT.STATUS IS 'Project status. Can be active or archived.';
COMMENT ON COLUMN APPDATA.PROJECT.CREATEDTIME IS 'Project created time. Default now.';
COMMENT ON COLUMN APPDATA.PROJECT.MODIFEDTIME IS 'Project modified time. Default now. Last project data update.';
